HW-1
vladnosiv/RogueLike-SD pull request #1
Opened 2022-03-20 21:50 UTC by vladnosiv

2022-03-20 22:25 UTC, vladnosiv commented
Часть задания в wiki

2022-03-20 23:27 UTC, vladnosiv commented
@uncerso

2022-05-15 10:49 UTC, yurii-litvinov requested changes
На вики не очень удобно комментить, так что напишу здесь:
- Нет единого документа, есть набор разрозненных страниц, которые непонятно, в каком порядке читать
- Общие сведения о системе надо бы подробнее, сейчас это ничем не отличается от условия. Например, придумать и описать концепцию игры.
- Половина ключевых функциональных требований ни разу не ключевые, а просто требования (никак особо на архитектуру не влияют). Дискретное время с тиками — да, это architectural driver, а что там с комнатами — чисто тактическая вещь. 
- Случаи использования тоже не вполне случаи использования на самом деле. Например, получение удовольствия от процесса — ну, скорее я как игрок хочу ненадолго отвлечься от работы и запускаю игру, чтобы получить удовольствие

Статическая структура:
- Из диаграммы компонентов не очень очевидно, как компоненты связаны. Например, View предоставляет интерфейс контроллеру?
- На диаграмме классов по мне так слишком мало связей. Вообще, если есть класс, к которому никакая ассоциация/зависимость не ведёт, это повод задуматься. Например, визуализировать связи между Environment и Mob и MainCharacter было бы лучше, чем просто нарисовать их полями (хотя бы потому, что я не прикопался бы к типу Mobs, которого на диаграмме нет).
- У вас UIEvent правда наследуется от ActorEvent и MapEvent, или должно быть наоборот? То же с ActorMoved и MapChanged, разве что тут из текстового описания понятно, что это на диаграмме ошибка, а UIEvent в текстовом описании не раскрыт.
- Кстати, интерфейсы в UML не так рисуются :)
- Стоило явно отразить компоненты на диаграмме классов (например, рисовать классы в символе компонентов, либо квалифицировать все имена классов компонентами, через `::`. Иначе непонятно, что к чему относится (ниже в тексте разбивка по компонентам есть, но текст не про все классы, и при рассматривании диаграммы это не помогает особо).
- Кто такой RMap, который упоминается как тип полей в классах в левом верхнем углу?
- ConcreteStrategy1/2 лучше заменить на конкретные стратегии из ТЗ

Поведение:
- На диаграмме последовательностей все линии жизни совпадают с линиями активации, это подозрительно (например, вряд ли KeyboardHandler что-то делает, пока кнопку не нажали, а у вас на диаграмме получается, что да (кстати, на диаграмме он KeyBoardHandler, что, наверное, неправильно))
- Создание объекта на диаграмме последовательностей рисуется пунктирной стрелкой без new: https://www.uml-diagrams.org/sequence-diagrams-reference.html
- На диаграмме конечных автоматов описание возможностей игрока следует вынести в комментарии, иначе это как-то неканонично
- И надо блок конца исполнения

2022-06-26 09:42 UTC, yurii-litvinov commented
- Тайловая графика — это не техническое ограничение, это часть ключевых функциональных требований. Технические ограничения — это про возможности платформы, аппаратного обеспечения и т.п., навязанных заказчиком. Вот поддержка Linux и MacOS — ок, управление с клавиатуры — тоже ок в том смысле, что игра предназначена для тех, у кого нет геймпада.
- 100% покрытие критических строк кода тестами — это не требование в общепринятом смысле, поскольку допускает свободу трактования. Что такое "критических"?

Диаграмма классов:
- Её можно было разместить менее компактно (в UML-рисовалке у вас бесконечная канва, этим надо пользоваться — иное дело, что бесконечную канву не заскриншотить) или побить на кусочки, и визуализировать ещё больше связей :) А то вот подсистема генерации карты ни с чем не связана.
- Реализация интерфейса рисуется пунктирной линией, не сплошной.
- Не надо дублировать ассоциации полями. Например, у Mob есть Strategy и State, это и так видно по стрелкам, поля тут только загромождают диаграмму. Кстати, у одного поля видимость private, у другого public, и оба они в интерфейсе, хотя интерфейс по идее не может иметь полей (впрочем, можно интерпретировать их как свойства).
- А ещё есть _зависимости_ (пунктирной стрелкой) и стереотипы зависимостей, например, `<<use>>`. Например, MapGenerator использует MapGeneratorConfig.
- `<ActionName>::handleModel()` UML не умеет, но ладно :) Однако стоит в комментарии написать, что это.

Диаграмма последовательностей:
- User способен к спонтанным действиям, следовательно его линия активации должна совпадать с его линией жизни.
- User вряд ли сам создаёт остальные объекты, их можно рисовать как уже данные. А если бы создавал, то это рисовалось бы стрелкой, входящей в объект слева, лучше со стереотипом `<<create>>` (я ж кидал ссылку на док).
- А вот Game на спонтанные действия не способен, так что вызов getPressed не может быть им инициирован, надо что-то, что его вызвало. Если хотите сказать, что в Game есть таймер, который иногда вычитывает команды из очереди, то стоит Game сделать линию активации, как User-у.

Диаграмма состояний:
- Конец игры не состояние, потому что система в нём не задерживается. Он-то и должен быть завершающим блоком.

В общем, в целом ок, но исправление мелких замечаний выше принесёт вам ещё полтора балла.

2022-08-01 02:03 UTC, merged