HW 2
vladnosiv/RogueLike-SD pull request #3
Opened 2022-04-10 23:11 UTC by Cabpacob

2022-06-12 17:36 UTC, yurii-litvinov requested changes
Тестов как-то уж совсем мало, хочется больше.

А ещё я правильно понимаю, что сейчас содержимое пространства имён model вообще не используется и не нужно? :) В этой задаче надо было всё-таки некий прототип настоящей архитектуры сделать, чтобы потом его расширять. Но условие задачи выполнено, вынужден признать, так что ок :)

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/Action.kt
> +// interface for transmitting information to the controller
Комментарии лучше в Dokka-формате, так-то зачем

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/Action.kt
> +package model
Пакет именован неканонично, надо поправить, чтобы там доменное имя было

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/Environment.kt
> +    val timer = Timer()
А тут точно всё должно быть public и половина мутабельной? Не может ли быть проблем с инкапсуляцией из-за этого?

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/MapGenerator.kt
> +    fun genMap(): Map
Лучше не сокращать идентификаторы. Тем более в мире JVM это не принято

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/view/Hero.kt
> + * Хранит класс игрока
О, комментарий в каноничном виде. Хочется, чтобы все такие были

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/view/Hero.kt
> +        if (y < 0) y = 0
Магические числа какие-то

2022-06-12 17:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/view/Map.kt
> +/**
```suggestion
import com.soywiz.korge.view.sprite

/**
```

2022-06-13 10:13 UTC, yurii-litvinov requested changes
Документацию ещё надо обновить, сейчас она не соответствует коду очень сильно.

И нужно больше тестов. Всякие стратегии-дектораторы и т.п. вообще не покрыты. Можно обойтись интеграционными тестами, впрочем.

И совсем беда с "продвинутыми" паттернами из 3 и 4 частей. Судя по устаревшей архитектуре, вы начали с кода, и получилось совсем не то, что нужно :)

2022-06-24 23:29 UTC, Cabpacob commented on src/commonMain/kotlin/model/Environment.kt
> +    val mobs = mutableListOf<Mob>()
Конкретно с этим классом все хорошо - он и позиционируется как контейнер, в котором хранятся объекты, которые относятся к игровому миру. А с инкапсуляцией все ок, к этому классу доступ имеют только те, кому это нужно, и никакой _секретной_ информации в нем не лежит

2022-06-24 23:32 UTC, Cabpacob commented on src/commonMain/kotlin/model/ModelHandler.kt
> +            else -> emptyList()
Проблема в том, что в разных местах разные Action'ы обрабатывать нужно по-разному. Например, в ModelHandler'е одно поведение, в Game другое, а в какой-то локальной обработке (как в Mob, например) третье. Поэтому было принято решение написать по одному большому свичу для каждой ситуации. К тому же эти действия не повторяются, да и не должны по логике (потому что это глобальный обработчик и никому больше не потребуется звать вообще все сущности)

2022-06-24 23:34 UTC, Cabpacob commented on src/commonMain/kotlin/model/ModelLogic.kt
> +    var lvl: Int = 0
Тут все тоже ок с доступностью, как и с Environment. По сути это и есть Environment, но еще и номер уровня, про который Environment знать не должен

2022-06-24 23:35 UTC, Cabpacob commented on src/commonMain/kotlin/model/map/MapLoader.kt
> +class MapLoader(levelName: String) : MapGenerator {
Потому что не припилили смену уровней, но в условии было требование реализовать загрузку уровня из файла

2022-06-24 23:39 UTC, Cabpacob commented on src/commonMain/kotlin/model/actors/mobs/PoisonousMold.kt
> +                    val newMob = this.replicate()
У ядовитой плесени есть параметр конструктора - вероятность воспроизведения. Наша идея была в том, чтобы у "детей" плесени вероятность воспроизведения была в два раза меньше чтобы она не могла заполнить всю карту
А если уметь клонировать вообще любого моба, то от этой фичи придется отказаться :(
При этом кто-то сбоку может вызвать replicate() ничего не зная о том, какой тип у моба, вроде все условия выполнены. И я не понял в чем проблема с тем, что мы сами себя копируем, это ж вроде логично :\

2022-06-25 07:24 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/Environment.kt
> +    val mobs = mutableListOf<Mob>()
Окей, но судя по коду Environment нужен стратегии, эффектам и ModelLogic. Причём стратегию и эффекты интересуют разные вещи, и вроде как не весь Environment. То есть, наверное, было бы лучше переместить содержимое Environment в ModelLogic, а остальным отдавать конкретные данные (типа списка мобов, карты и т.п.), причём в немутабельном виде. Interface Segregation Principle в действии.

Впрочем, можно не переделывать.

2022-06-25 07:26 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/ModelHandler.kt
> +            else -> emptyList()
То есть у нас ситуация, когда требуемое действие зависит от рантайм-типа команды и рантайм-типа Receiver-а, то есть требуется _двойная диспетчеризация_. Может помочь паттерн Visitor :)

2022-06-25 07:27 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/map/MapLoader.kt
> +class MapLoader(levelName: String) : MapGenerator {
Ну, можно либо припилить-таки смену уровней (дошли до нужной клетки — грузится следующий), либо сделать опцию командной строки, которая говорит игре, инициализироваться случайной картой или загрузиться.

2022-06-25 07:36 UTC, yurii-litvinov commented on src/commonMain/kotlin/model/actors/mobs/PoisonousMold.kt
> +                    val newMob = this.replicate()
В том, что копируете сами себя, никакой проблемы нет, проблема в том, что **только** сами себя :) Проблему с вероятностью воспроизведения можно решить тем, что плесень, зная, что она плесень, после создания клона может ему менять вероятность воспроизведения сама, прямо в replicate(). Если у кого-то из будущих реплицирующихся объектов такой фичи не будет, они могут её просто не реализовывать.

(Кстати, в классическом ADOM был бесполезный артефакт, неконтролируемо реплицирующийся в инвентаре: https://ancardia.fandom.com/wiki/Si, по легенде — как шутка по поводу того, что в настольных RPG инвентарь ведётся ручкой на бумаге и быстро заполняется разными кляксами. Так что реплицироваться могут не только мобы).

2022-06-25 07:57 UTC, yurii-litvinov requested changes
А в целом по паттернам всё так. Мне кажется, надо всё-таки что-то сделать с паттерном "Команда", попробуйте реализовать в духе Visitor-а, а если не получится, то пусть команды имеют разные execute для разных Receiver-ов. Не то чтобы это сильно нужно в вашей архитектуре, у вас по сути событийная схема получилась. Но условие требует :) Ну и надо доделывать — юнит-тесты, комментарии и т.п.

2022-06-25 07:57 UTC, yurii-litvinov commented on src/commonMain/kotlin/com/hse/sd/roguelike/model/actors/mobs/AbstractMobFactory.kt
> +interface AbstractMobFactory {
Комментариев не хватает :)

2022-06-25 07:57 UTC, yurii-litvinov commented on src/commonMain/kotlin/com/hse/sd/roguelike/model/EnvironmentBuilder.kt
> +//        environment.mobs.addAll(mobs)
```suggestion
```

2022-08-01 03:02 UTC, merged